name: gemini_app
description: A Flutter application using Gemini API
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  lottie: ^2.3.2
  google_fonts: ^5.1.0
  animated_text_kit: ^4.2.2
  flutter_markdown: ^0.6.18
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env